/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCard: typeof import('./../src/components/AppCard.vue')['default']
    CommonTable: typeof import('./../src/components/CommonTable.vue')['default']
    MdEditor: typeof import('./../src/components/MdEditor.vue')['default']
    MdViewer: typeof import('./../src/components/MdViewer.vue')['default']
    PictureUpload: typeof import('./../src/components/PictureUpload.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
